givenName = input("What is your given name?")
lastName = input("What is your last name?")
streetAddress = input("What is your street address?")
city = input("What is your city and postal code?")
print(givenName + " " + lastName)
print(streetAddress)
print(city)
